version: "3.8"
networks:
  task:
services:
  php:
    build:
      args:
        user: nader
        uid: 1000
      context: ./docker/services/php83
    container_name: '4sale-php83'
    restart: always
    expose:
      - "9000"
    volumes:
      - /:/var/www/html
    networks:
      - task
  webserver:
    build:
      context: ./env/services/${WEB_SERVER}
    container_name: '4sale-nginx'
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /:/var/www/html
      - ./docker/config/nginx:/etc/nginx/conf.d
      - ./docker/storage/nginx/logs:/var/log/nginx
    depends_on:
      - php
    networks:
      - task
